# Generated by Django 2.2.2 on 2019-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaRecursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=140)),
                ('tipo', models.CharField(choices=[('portatil', 'Portátil'), ('nportatil', 'Não Portátil')], max_length=15)),
                ('categoria', models.CharField(blank=True, choices=[('espacos', 'Espaço'), ('acessorios', 'Acessórios'), ('computadores', 'Computadores'), ('projetores', 'Projetores'), ('moveis', 'Móveis')], max_length=20)),
                ('estado', models.CharField(blank=True, choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('indisponivel', 'Indisponível'), ('emprestado', 'Emprestado')], default='disponivel', max_length=20)),
                ('setor', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('identificador', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=140)),
                ('tipo', models.CharField(choices=[('portatil', 'Portátil'), ('nportatil', 'Não Portátil')], max_length=15)),
                ('categoria', models.CharField(choices=[('espacos', 'Espaço'), ('acessorios', 'Acessórios'), ('computadores', 'Computadores'), ('projetores', 'Projetores'), ('moveis', 'Móveis')], max_length=20)),
                ('estado', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('indisponivel', 'Indisponível'), ('emprestado', 'Emprestado')], default='disponivel', max_length=20)),
                ('setor', models.CharField(max_length=20)),
                ('TMA', models.IntegerField()),
                ('TMR', models.IntegerField()),
                ('TMAP', models.IntegerField()),
                ('MDI', models.CharField(blank=True, max_length=140)),
            ],
        ),
    ]
