# Generated by Django 2.2.2 on 2019-06-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=140)),
                ('tipo', models.CharField(max_length=15)),
                ('categoria', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('indisponivel', 'Indisponível'), ('emprestado', 'Emprestado')], default='disponivel', max_length=20)),
                ('setor', models.CharField(max_length=20)),
                ('TMA', models.IntegerField()),
                ('TMR', models.IntegerField()),
                ('TMAP', models.IntegerField()),
                ('MDI', models.CharField(max_length=140)),
            ],
        ),
    ]
