# Generated by Django 2.2.2 on 2019-06-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0002_auto_20190615_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisarecursos',
            name='tipo',
            field=models.CharField(choices=[('portatil', 'Portátil'), ('nportatil', 'Não Portátil')], max_length=15),
        ),
    ]
