# Generated by Django 2.2.2 on 2019-06-17 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('identificador', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('estado', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada')], max_length=9, verbose_name='Estado')),
                ('data_aprovacao', models.DateTimeField(auto_now_add=True, verbose_name='Aprovado em')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Devolvido em')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reserva.Reserva')),
            ],
            options={
                'verbose_name': 'Alocação',
                'verbose_name_plural': 'Alocações',
                'ordering': ('data_aprovacao',),
            },
        ),
    ]
