# Generated by Django 2.2.2 on 2019-06-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('matricula', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=140, verbose_name='Nome')),
                ('usuario', models.CharField(max_length=15, unique=True, verbose_name='Usuário')),
                ('setor', models.CharField(max_length=20, verbose_name='Setor')),
                ('cargo', models.CharField(choices=[('membro', 'Membro'), ('responsavel', 'Responsável'), ('administrador', 'Administrador')], max_length=13, verbose_name='Cargo')),
                ('recursos', models.ManyToManyField(to='recurso.Recurso')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ('usuario',),
            },
        ),
    ]
